### 1. 创建一个长度为10的一维全为0的ndarray对象，然后让第5个元素等于1

In [1]:
import numpy as np
a=np.zeros(10)
print((a))
a[4]=1
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


### 2. 创建一个元素为从10到49的ndarray对象
2.1 包含20个元素  
2.2 每隔3取值一个元素

In [2]:
#2 从10到49的ndarray对象
a=np.arange(10,50)
print(a)
#2.1 包含20个元素的ndarray对象
b=np.linspace(10,49,20)
print(b)
#2.2 每隔3取值一个元素
c=np.arange(10,50,3)
print(c)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[10.         12.05263158 14.10526316 16.15789474 18.21052632 20.26315789
 22.31578947 24.36842105 26.42105263 28.47368421 30.52631579 32.57894737
 34.63157895 36.68421053 38.73684211 40.78947368 42.84210526 44.89473684
 46.94736842 49.        ]
[10 13 16 19 22 25 28 31 34 37 40 43 46 49]


### 3. 将2中最后一个ndarray翻转

In [3]:
reverse=c[::-1]
print(reverse)

[49 46 43 40 37 34 31 28 25 22 19 16 13 10]


### 4. 使用np.random.random创建一个10*10的ndarray对象，并打印出最大最小元素

In [4]:
d=np.random.random((10,10))
print(d)
print(d.max())
print(d.min())

[[0.34578745 0.56639591 0.99664027 0.85602469 0.89305919 0.51124505
  0.55710192 0.66108637 0.97355849 0.29858689]
 [0.20933173 0.27488837 0.28932156 0.97443006 0.95074973 0.99188276
  0.11062929 0.64854988 0.09637194 0.6884315 ]
 [0.77006751 0.04454318 0.7678962  0.35483661 0.40092694 0.39866748
  0.24898464 0.99140972 0.13093072 0.29937234]
 [0.5642781  0.03688415 0.31969461 0.55159294 0.51711676 0.03866863
  0.51798733 0.04657241 0.59306407 0.05532315]
 [0.96096777 0.05033348 0.93778768 0.88801659 0.37706054 0.72049904
  0.05722718 0.22625763 0.57821057 0.17171592]
 [0.89435393 0.1867381  0.26401643 0.51591635 0.96995919 0.25197118
  0.12454048 0.49482746 0.50933763 0.71122083]
 [0.42196902 0.81677275 0.63097416 0.19823636 0.07993046 0.1034908
  0.71978026 0.67990044 0.47987538 0.12760028]
 [0.36347839 0.85255811 0.68299773 0.44738038 0.65155177 0.36866769
  0.28249931 0.91853045 0.79855712 0.3136806 ]
 [0.00104746 0.01765069 0.50039523 0.82616514 0.51838757 0.76680577
  0.73806754 

### 5. 创建一个10*10的ndarray对象，且矩阵边界全为1，里面全为0

In [5]:
e=np.zeros((10,10))
e[[0,9]]=1
e[:,[0,9]]=1
print(e)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


### 6. 创建一个每一行都是从0到4的5*5矩阵

In [6]:
f=np.array([0,1,2,3,4]*5).reshape(5,5)
print(f)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


### 7. 创建一个长度为10的随机数组并将最大值替换为0

In [8]:
g=np.random.randint(0,100,10)
print(g)
gmax=g.max()
gmaxwhere=g==gmax #g==max returns an ndarray containing true, false, ...(only one "true" when it indexes the max value.)
g[gmaxwhere]=0
print(g)

[97 45 22 49 67 92  9 60 27  3]
[ 0 45 22 49 67 92  9 60 27  3]


### 8. 生成长度为10的随机数组m
8.1 运行print(t.argsort())  
8.2 运行t.sort()  
比较两个排序命令的区别

In [9]:
m=np.random.randint(0,100,10)
print(m)
#8.1
print(m.argsort())
#8.2
m.sort()
print(m)

#区别：print(t.argsort())将数组按从小到大排列，并按照对应的索引值输出；sort()在原数组上进行从小到大的重新排序。

[ 3 25 76 95 27  8  8 55 22 85]
[0 5 6 8 1 4 7 2 9 3]
[ 3  8  8 22 25 27 55 76 85 95]


### 9. 给定一个4维矩阵，如何得到最后两维的和？
可使用np.random.randint(0,10,(3,3,3,3))生成0到9范围内的随机整数矩阵

In [10]:
h=np.random.randint(0,10,(3,3,3,3))
j=h.sum(axis=(-1,-2))
print(j)

[[43 40 42]
 [46 47 40]
 [30 54 32]]


### 10. 给定数组[1, 2, 3, 4, 5]，如何得到在这个数组的每个元素之间插入3个0后的新数组？

In [11]:
o=np.arange(1,6)
p=np.zeros(17,dtype=np.int8)
p[::4]=o
print(p)

[1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5]


### 11. 给定一个二维矩阵，如何交换其中两行的元素？

In [12]:
q=np.random.randint(0,100,(3,3))
print(q)
print(q[[1,0,2]])

[[25  3 98]
 [12 10 28]
 [57 61 93]]
[[12 10 28]
 [25  3 98]
 [57 61 93]]


### 12. 创建一个5 \* 3 随机矩阵和一个3 \* 2随机矩阵，求矩阵积

In [13]:
r=np.random.randint(0,10,(5,3))
s=np.random.randint(0,10,(3,2))
product=np.dot(r,s)
print(r)
print(s)
print(product)

[[6 1 4]
 [4 0 0]
 [9 7 5]
 [0 4 5]
 [7 4 8]]
[[6 9]
 [4 6]
 [4 9]]
[[ 56  96]
 [ 24  36]
 [102 168]
 [ 36  69]
 [ 90 159]]


### 13. 生成一个5 \*5 的0到10之间的随机整数矩阵，矩阵的每一行的元素都减去该行的平均值

In [14]:
u=np.random.randint(0,11,(5,5))
print(u)
average=u.mean(axis=1).reshape(5,1)
print(average)
u=u-average 
print(u)

[[ 0  1  1  9  4]
 [ 8  3  3  9  1]
 [ 4  5  4  4  2]
 [ 1  7 10  7  0]
 [ 5  6  8  1  8]]
[[3. ]
 [4.8]
 [3.8]
 [5. ]
 [5.6]]
[[-3.  -2.  -2.   6.   1. ]
 [ 3.2 -1.8 -1.8  4.2 -3.8]
 [ 0.2  1.2  0.2  0.2 -1.8]
 [-4.   2.   5.   2.  -5. ]
 [-0.6  0.4  2.4 -4.6  2.4]]


### 14. 生成如下矩阵：
[[0 1 0 1 0 1 0 1]  
 [1 0 1 0 1 0 1 0]  
 [0 1 0 1 0 1 0 1]  
 [1 0 1 0 1 0 1 0]  
 [0 1 0 1 0 1 0 1]  
 [1 0 1 0 1 0 1 0]  
 [0 1 0 1 0 1 0 1]  
 [1 0 1 0 1 0 1 0]  
 14.1 要求使用np.zeros创建8*8的矩阵  
 14.2 np.fromfunction创建

In [15]:
#14.1
v=np.zeros((8,8),dtype=np.int8)
v[::2,1::2]=1
v[1::2,::2]=1
print(v)

#14.2
def fun(x,y):
    return((x+y)%2)
w=np.fromfunction(fun,(8,8),dtype=np.int8)
print(w)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### 15、正则化一个5\*5随机矩阵  
【正则的概念：假设a是矩阵中的一个元素，max/min分别是矩阵元素的最大最小值，则正则化后a = (a - min)/(max - min)】

In [16]:
z=np.random.randint(0,100,size=(5,5))
print(z)
zmin=a.min()
zmax=a.max()
z=(z-zmin)/(zmax-zmin)
print(z)

[[24 40 39 20 75]
 [41 82 18 60 34]
 [97 30 66 60 57]
 [20 49 43 96 38]
 [93  2 46  1 76]]
[[ 0.35897436  0.76923077  0.74358974  0.25641026  1.66666667]
 [ 0.79487179  1.84615385  0.20512821  1.28205128  0.61538462]
 [ 2.23076923  0.51282051  1.43589744  1.28205128  1.20512821]
 [ 0.25641026  1.          0.84615385  2.20512821  0.71794872]
 [ 2.12820513 -0.20512821  0.92307692 -0.23076923  1.69230769]]
